# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]
      ROLE_ADMIN: [ROLE_USER, ROLE_USER_ADMIN, ROLE_PARTICIPANT_ADMIN]

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            logout:
               path: /logout
               target: /

            form_login:
                login_path: login
                check_path: login
                use_referer: true
                always_use_default_target_path: true
                default_target_path: /panel

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                httponly: true
                remember_me_parameter: remember_me

dunglas_angular_csrf:
  # Collection of patterns where to set the cookie
  cookie:
      set_on:
        - {route: ^homepage, methods: [GET]}
  secure:
    - {route: ^registration_email_contact, methods:[POST]}
